[Appearance]
style=Fusion
color_scheme_path=~/.config/qt6ct/colors/catppuccin-mocha.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default

[Fonts]
fixed="FiraCode Nerd Font Mono,11,-1,5,50,0,0,0,0,0"
general="FiraCode Nerd Font,11,-1,5,50,0,0,0,0,0"

[Interface]
cursor_flash_time=1000
double_click_interval=400
gui_effects=@Invalid()
menus_have_icons=true
show_shortcuts_in_context_menus=true
toolbutton_style=4
wheel_scroll_lines=3
