# ~/.config/hypr/general.conf
# Anything here should be safe on ANY machine (GPU-agnostic).

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(89b4faee) rgba(cba6f7ee) 45deg
    col.inactive_border = rgba(45475aaa)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 2
}

animations {
    enabled = true
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = snappy, 0.1, 0.9, 0.1, 1

    animation = windows, 1, 2, snappy
    animation = fade, 1, 2, snappy
    animation = workspaces, 1, 2, snappy
    animation = border, 1, 2, snappy
}

dwindle {
    preserve_split = true
}

input {
    kb_layout = no
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

gestures {
    gesture = 3, horizontal, workspace 
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
}
