# ~/.config/hypr/keybinds.conf

$mod = SUPER
$terminal = kitty
$launcher = rofi -show drun
$browser = brave-browser
$filemanager = nautilus

bind = $mod, Return, exec, $terminal
bind = $mod, Q, killactive
bind = $mod, M, exit
bind = $mod, E, exec, $filemanager
bind = $mod, V, togglefloating
bind = $mod, R, exec, $launcher
bind = $mod, J, togglesplit
bind = $mod, F, fullscreen

# power menu
bind = $mod SHIFT, X, exec, wlogout

# clipboard history (cliphist is populated by autostart.conf)
bind = $mod, C, exec, cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy

# focus movement
bind = $mod, h, movefocus, l
bind = $mod, l, movefocus, r
bind = $mod, k, movefocus, u
bind = $mod, j, movefocus, d

# window movement
bind = $mod SHIFT, h, movewindow, l
bind = $mod SHIFT, l, movewindow, r
bind = $mod SHIFT, k, movewindow, u
bind = $mod SHIFT, j, movewindow, d

# workspaces 1-10
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# media / volume (works on both desktop + laptop)
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 5%-

# notifications (mako)
bind = $mod, N, exec, makoctl dismiss
bind = $mod SHIFT, N, exec, makoctl restore

# Screenshots (Hyprshot)
bind = , Print, exec, hyprshot -m output                       # full screen
bind = $mod, Print, exec, hyprshot -m region                   # click-drag region
