# ~/.config/hypr/windowrules.conf

windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(Picture-in-Picture)$, float on
windowrule = match:class ^(Picture-in-Picture)$, pin on
