-- AstroUI provides the basis for configuring the AstroNvim User Interface
-- Configuration documentation can be found with `:h astroui`
-- NOTE: We highly recommend setting up the Lua Language Server (`:LspInstall lua_ls`)
--       as this provides autocomplete and documentation while editing

-- palette.lua is generated by scripts/theme.sh from palettes/<name>.env -- the
-- same file the bar, the window borders and the lock screen are built from.
local p = require "palette"

---@type LazySpec
return {
  "AstroNvim/astroui",
  ---@type AstroUIOpts
  opts = {
    -- change colorscheme
    colorscheme = "zenwritten",
    -- AstroUI allows you to easily modify highlight groups easily for any and all colorschemes
    highlights = {
      -- Chrome only. zenwritten owns syntax, diagnostics and diffs; these
      -- overrides exist so the parts of nvim that sit *next to* the desktop --
      -- the background, the split seams, float borders, the statusline --
      -- land on the exact same greys as waybar and the window borders.
      --
      -- An editor one shade off the desktop looks worse than one that makes no
      -- attempt to match, because the near-miss is what the eye picks up.
      zenwritten = {
        Normal = { bg = p.bg, fg = p.text },
        NormalNC = { bg = p.bg },
        NormalFloat = { bg = p.bg_alt, fg = p.text },
        FloatBorder = { bg = p.bg_alt, fg = p.border },
        FloatTitle = { bg = p.bg_alt, fg = p.text },

        -- Splits are a 1px seam in @border, matching gaps_in/border_size in
        -- hypr/general.lua. Default is a filled bar, which reads as a panel.
        WinSeparator = { fg = p.border, bg = p.bg },
        VertSplit = { fg = p.border, bg = p.bg },

        StatusLine = { bg = p.bg_alt, fg = p.dim },
        StatusLineNC = { bg = p.bg_alt, fg = p.muted },

        SignColumn = { bg = p.bg },
        LineNr = { fg = p.muted, bg = p.bg },
        CursorLineNr = { fg = p.text, bg = p.surface },
        CursorLine = { bg = p.bg_alt },

        Visual = { bg = p.surface_hi },

        -- Snacks picker (find_files, buffers, leetcode's question list, ...)
        -- renders in a float whose bg is NormalFloat (bg_alt). Its cursor-row
        -- highlight defaults to a plain link to CursorLine, whose bg is *also*
        -- bg_alt -- identical colors, so the current row was invisible and
        -- only the Tab multi-select dot read as "selection". The dot itself
        -- is blanked out instead of recolored -- see plugins/snacks.lua.
        SnacksPickerListCursorLine = { bg = p.surface_hi },

        Pmenu = { bg = p.surface, fg = p.text },
        PmenuSel = { bg = p.surface_hi, fg = p.accent },
        PmenuSbar = { bg = p.surface },
        PmenuThumb = { bg = p.border },

        Comment = { fg = p.muted, italic = true },

        -- Tab line, mirroring the bar: inactive is recessed, active is the one
        -- bright thing.
        TabLine = { bg = p.bg_alt, fg = p.muted },
        TabLineFill = { bg = p.bg_alt },
        TabLineSel = { bg = p.bg, fg = p.accent },

        -- Differentiation via weight/slant/brightness instead of hue --
        -- zenbones' own trick elsewhere (Comment/String are already italic,
        -- Statement is already bold). Same grays already in the palette, no
        -- new colors, so it stays monochrome.
        Type = { fg = p.text, bold = true }, -- types, classes, interfaces, structs, enums: brighter + bold
        ["@type"] = { link = "Type" },
        ["@lsp.type.class"] = { link = "Type" },
        ["@lsp.type.interface"] = { link = "Type" },
        ["@lsp.type.struct"] = { link = "Type" },
        ["@lsp.type.enum"] = { link = "Type" },

        Function = { bold = true }, -- function/method names: same gray, just bold
        ["@function"] = { link = "Function" },
        ["@function.call"] = { link = "Function" },
        ["@method"] = { link = "Function" },
        ["@method.call"] = { link = "Function" },

        -- Parameters read as subordinate to locals: dimmer and italic, the
        -- same visual language zenwritten already uses for Comment.
        ["@variable.parameter"] = { fg = p.dim, italic = true },
        ["@lsp.type.parameter"] = { link = "@variable.parameter" },
      },
    },
    -- Icons can be configured throughout the interface
    icons = {
      -- configure the loading of the lsp in the status line
      LSPLoading1 = "⠋",
      LSPLoading2 = "⠙",
      LSPLoading3 = "⠹",
      LSPLoading4 = "⠸",
      LSPLoading5 = "⠼",
      LSPLoading6 = "⠴",
      LSPLoading7 = "⠦",
      LSPLoading8 = "⠧",
      LSPLoading9 = "⠇",
      LSPLoading10 = "⠏",
    },
  },
}
